### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by gunar** [twolfson/esformatter-phonetic#3]
What's the use case?

**Comment by twolfson** [comment]
Explained in the README =P Here's a copy/paste:

This was built to make reading obfuscated scripts easier (e.g. expand a single character variable to a full name, `a` -> `apple`). It was inspired by [`beautify-with-words`][] but we wanted to leverage other [`esformatter`][] plugins.

[`beautify-with-words`]: https://github.com/zertosh/beautify-with-words
[`esformatter`]: https://github.com/millermedeiros/esformatter
